---
apiVersion: v1
kind: Service
metadata:
  name: konnectivity-server-agent
  labels:
    app: konnectivity-server
spec:
  type: NodePort
  selector:
    app: konnectivity-server
  ports:
    - name: konnectivity-agent
      port: {{ .KonnectivityAgentPort }}
      targetPort: {{ .KonnectivityAgentPort }}
{{- if .KonnectivityServerAgentNodePort }}
      nodePort: {{ .KonnectivityServerAgentNodePort }}
{{- end }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: konnectivity-server
  labels:
    app: konnectivity-server
spec:
  type: ClusterIP
  selector:
    app: konnectivity-server
  ports:
    - name: konnectivity-server
      port: {{ .KonnectivityServerPort }}
      targetPort: {{ .KonnectivityServerPort }}
      protocol: TCP
