apiVersion: v1
kind: Secret
metadata:
  name: konnectivity-agent
  namespace: kube-system
data:
  konnectivity-agent.pem: {{ pki "konnectivity-agent.pem" }}
  konnectivity-agent-key.pem: {{ pki "konnectivity-agent-key.pem" }}
