---
apiVersion: v1
kind: Service
metadata:
  name: konnectivity-server-{{ .ClusterID }}-agent
  labels:
    app: konnectivity-server
spec:
  ports:
    - name: konnectivity-agent
      port: {{ .KonnectivityAgentPort }}
      targetPort: {{ .KonnectivityAgentPort }}
{{- if .KonnectivityServerAgentNodePort }}
      nodePort: {{ .KonnectivityServerAgentNodePort }}
{{- end }}
      protocol: TCP
  selector:
    app: konnectivity-server
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: konnectivity-server
  labels:
    app: konnectivity-server
spec:
  ports:
    - name: konnectivity-server
      port: {{ .KonnectivityServerPort }}
      targetPort: {{ .KonnectivityServerPort }}
      protocol: TCP
  selector:
    app: konnectivity-server
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: konnectivity-server-metrics
  labels:
    app: konnectivity-server
  annotations:
    prometheus.io/probe: 'true'
    prometheus.io/scrape: 'true'
    prometheus.io/probepath: 'metrics'
spec:
  ports:
    - name: metrics
      port: {{ .KonnectivityServerAdminPort }}
      targetPort: {{ .KonnectivityServerAdminPort }}
      protocol: TCP
  selector:
    app: konnectivity-server